// api.js
const products = [
    {
      id: 1,
      name: "Протеин Whey",
      description: "Высококачественный сывороточный протеин на основе сыворотки, который быстро усваивается организмом. Идеален для использования после тренировки для поддержания роста мышечной массы.",
      price: 2500,
      category: "Протеин",
      image: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/opn/opn02412/y/37.jpg",
      nutrients: {
        protein: "24g",
        carbs: "3g",
        fat: "1g",
      },
      servingSize: "30g",
    },
    {
      id: 2,
      name: "Аминокислоты BCAA",
      description: "Смешанные аминокислоты, которые помогают восстанавливать мышцы и стимулируют их рост. Отлично подходят для приема до и после тренировки.",
      price: 1500,
      category: "Аминокислоты",
      image: "https://basket-01.wbbasket.ru/vol90/part9055/9055309/images/big/1.webp",
      nutrients: {
        protein: "5g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "10g",
    },
    {
      id: 3,
      name: "Спортивные орехи",
      description: "Смешанные орехи, богатые белками и полезными жирами. Эти орехи идеально подходят для перекуса во время тренировок или в течение дня, обеспечивая необходимую энергию.",
      price: 400,
      category: "Снеки",
      image: "https://sport-dealer.ru/wa-data/public/shop/products/50/81/8150/images/11630/11630.240@2x.jpg",
      nutrients: {
        protein: "6g",
        carbs: "15g",
        fat: "12g",
      },
      servingSize: "30g",
    },
    {
      id: 4,
      name: "Протеиновый батончик",
      description: "Удобный перекус, содержащий 20 г белка на порцию. Идеален для поддержания уровня энергии и восстановления после тренировок.",
      price: 600,
      category: "Снеки",
      image: "https://goods-photos.static1-sima-land.com/items/7941649/0/700-nw.jpg",
      nutrients: {
        protein: "20g",
        carbs: "25g",
        fat: "7g",
      },
      servingSize: "60g",
    },
    {
      id: 5,
      name: "Сухофрукты для перекуса",
      description: "Смесь сушеных фруктов, идеально подходящая для здорового перекуса. Обеспечивает энергией и витаминами в течение дня.",
      price: 500,
      category: "Снеки",
      image: "https://d9ae6ad5-3627-4bf2-85a7-22bbd5549e94.selcdn.net/uploads/picture/picture/471119/large_file.jpeg",
      nutrients: {
        protein: "2g",
        carbs: "25g",
        fat: "1g",
      },
      servingSize: "40g",
    },
    {
      id: 6,
      name: "Энергетический напиток",
      description: "Напиток, повышающий уровень энергии и выносливости во время тренировок. Содержит витамины и минералы, поддерживающие здоровье.",
      price: 250,
      category: "Напитки",
      image: "https://cdn-img.perekrestok.ru/i/800x800-fit/xdelivery/files/39/c3/626c0ec12d7aa3fff72604db956b.jpg",
      nutrients: {
        protein: "0g",
        carbs: "35g",
        fat: "0g",
      },
      servingSize: "500ml",
    },
    {
      id: 7,
      name: "Спортивная каша",
      description: "Полезная каша, богатая углеводами и белками. Идеально подходит для завтрака или перекуса перед тренировкой.",
      price: 400,
      category: "Питание",
      image: "https://ecotopia.ru/static/36c255b8-bab4-4faf-881a-05729efe24a4.jpg",
      nutrients: {
        protein: "10g",
        carbs: "50g",
        fat: "5g",
      },
      servingSize: "100g",
    },
    {
      id: 8,
      name: "Спортивный шейкер",
      description: "Шейкер для приготовления протеиновых коктейлей. Удобен для использования в любых условиях — дома, в спортзале или в поездках.",
      price: 300,
      category: "Аксессуары",
      image: "https://www.gadget.kg/upload/catalog/21/item_2043/33ca600186f1f5fafd45a381e54560a8.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 9,
      name: "Спортивные перчатки",
      description: "Перчатки для тренировок с весами. Обеспечивают надежный захват и защищают ладони от травм.",
      price: 1000,
      category: "Аксессуары",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSziEDT-ytdZiApIDgRj30BOKYYB-nL-6wjug&s",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 10,
      name: "Спортивная бутылка",
      description: "Удобная бутылка для воды с функцией предотвращения протекания. Идеально подходит для тренировки и активного отдыха.",
      price: 250,
      category: "Аксессуары",
      image: "https://www.gadget.kg/upload/catalog/6/item_554/3bab1b4976e31d377bc3b541d8f6f475.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 11,
      name: "Спортивные кроссовки",
      description: "Легкие и удобные кроссовки, разработанные для тренировок. Обеспечивают отличную поддержку и амортизацию.",
      price: 3000,
      category: "Обувь",
      image: "https://goods-photos.static1-sima-land.com/items/7915794/0/700-nw.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 12,
      name: "Спортивная одежда",
      description: "Удобная и дышащая одежда, специально разработанная для тренировок. Обеспечивает свободу движений и комфорт.",
      price: 2000,
      category: "Одежда",
      image: "https://ryazan.vse-footbolki.ru/image/cache/catalog/vsm/0/2/2839/2839981/previews/people_8_woman_knit_suit_front_white_700-280x280.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 13,
      name: "Энергетические батончики",
      description: "Энергетические батончики, которые обеспечивают быструю энергию во время тренировок и помогают предотвратить усталость.",
      price: 700,
      category: "Снеки",
      image: "https://whey.kz/wp-content/uploads/2023/12/prime-kraft-primebar-crunch-40-g-2-scaled.jpg",
      nutrients: {
        protein: "15g",
        carbs: "40g",
        fat: "8g",
      },
      servingSize: "50g",
    },
    {
      id: 14,
      name: "Соленые орехи",
      description: "Соленые орехи для перекуса, богаты белками и полезными жирами. Отличный вариант для перекуса в пути.",
      price: 450,
      category: "Снеки",
      image: "https://main-cdn.sbermegamarket.ru/big1/hlr-system/-30/968/206/897/171/8/100036968502b0.jpg",
      nutrients: {
        protein: "7g",
        carbs: "10g",
        fat: "15g",
      },
      servingSize: "30g",
    },
    {
      id: 15,
      name: "Спортивные мюсли",
      description: "Мюсли, содержащие много клетчатки и полезных углеводов. Идеально подходят для завтрака или перекуса.",
      price: 400,
      category: "Питание",
      image: "https://main-cdn.sbermegamarket.ru/mid9/hlr-system/212/876/355/871/217/17/600001703337b0.jpg",
      nutrients: {
        protein: "8g",
        carbs: "50g",
        fat: "6g",
      },
      servingSize: "100g",
    },
    {
      id: 16,
      name: "Протеиновая паста",
      description: "Паста, обогащенная белком, которая идеально подходит для спортивного питания. Легко готовится и имеет отличный вкус.",
      price: 800,
      category: "Питание",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv4FR4dpJ4fPSaDXMPZ3yAv19pusmlLkN1MA&s",
      nutrients: {
        protein: "15g",
        carbs: "45g",
        fat: "2g",
      },
      servingSize: "100g",
    },
    {
      id: 17,
      name: "Спортивный крем для мышц",
      description: "Крем для разогрева мышц перед тренировкой и для восстановления после нагрузки. Облегчает боль и усталость.",
      price: 600,
      category: "Уход",
      image: "https://piroche.ru/img/catalog/510x560/610.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 18,
      name: "Протеиновый коктейль",
      description: "Готовый к употреблению коктейль с высоким содержанием белка. Отлично подходит для быстрого перекуса после тренировки.",
      price: 300,
      category: "Напитки",
      image: "https://www.herbalife.kg/upload/iblock/605/6mshfdbkewyuo6ikx1k971uqmn2vp1hb/F1_Vanilla%20cream_508%D1%85685%20(1).jpg",
      nutrients: {
        protein: "20g",
        carbs: "30g",
        fat: "5g",
      },
      servingSize: "250ml",
    },
    {
      id: 19,
      name: "Спортивный гель",
      description: "Гель для энергии, содержащий углеводы и электролиты. Идеально подходит для длительных тренировок.",
      price: 150,
      category: "Напитки",
      image: "https://static.siberianhealth.com/public/projects/shopen/images/41/_resize/410054_new_73e8849d_fit_300_300.jpg",
      nutrients: {
        protein: "0g",
        carbs: "23g",
        fat: "0g",
      },
      servingSize: "40g",
    },
    {
      id: 20,
      name: "Батончик из протеиновой муки",
      description: "Батончик с высоким содержанием белка, который отлично подходит для перекуса. Содержит натуральные ингредиенты.",
      price: 500,
      category: "Снеки",
      image: "https://wee-prod-public.s3.eu-central-1.amazonaws.com/62803d43/9a53b1a1/47e2196d/b09320a6/65a09cb8939452.82452255.medium.jpg",
      nutrients: {
        protein: "18g",
        carbs: "25g",
        fat: "7g",
      },
      servingSize: "60g",
    },
    {
      id: 21,
      name: "Спортивные рога",
      description: "Специальные рога для тренировок на воздухе, обеспечивающие комфорт и поддержку во время занятий.",
      price: 1200,
      category: "Аксессуары",
      image: "https://sportexpert.kg/wp-content/uploads/2020/07/35120_hlavni.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 22,
      name: "Спортивный пояс",
      description: "Пояс для поддержки спины во время тренировок с весами. Обеспечивает безопасность и комфорт.",
      price: 900,
      category: "Аксессуары",
      image: "https://bishkek.sport96.ru/uploadedFiles/eshopimages/big/548942783_w640_h640_548942783.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 23,
      name: "Спортивный массажный мяч",
      description: "Массажный мяч для расслабления мышц после тренировок. Помогает снизить напряжение и улучшить кровообращение.",
      price: 700,
      category: "Аксессуары",
      image: "https://image-thumbs.shafastatic.net/1377048326_310_430",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 24,
      name: "Спортивный ролик",
      description: "Ролик для тренировки пресса и других мышц. Укрепляет основные группы мышц и улучшает координацию.",
      price: 800,
      category: "Аксессуары",
      image: "https://main-cdn.sbermegamarket.ru/big2/hlr-system/-16/493/024/421/222/235/3/600006346830b8.jpeg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 25,
      name: "Фитнес-резинки",
      description: "Резинки для фитнеса, которые отлично подходят для тренировок дома и в зале. Помогают увеличить интенсивность тренировок.",
      price: 500,
      category: "Аксессуары",
      image: "https://protei.kg/wp-content/uploads/2020/12/i_001973.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 26,
      name: "Суперфуды",
      description: "Суперфуды для поддержания общего здоровья и иммунной системы. Содержат витамины и минералы.",
      price: 700,
      category: "Питание",
      image: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/foa/foa01710/y/8.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 27,
      name: "Энергетические чаи",
      description: "Чай с добавлением экстрактов растений, который повышает уровень энергии и улучшает концентрацию.",
      price: 350,
      category: "Напитки",
      image: "https://aidigo.ru/upload/resize_cache/webp/iblock/315/uqzree33eo0i6bpm1z48nkbwen89a0x6.webp",
      nutrients: {
        protein: "0g",
        carbs: "5g",
        fat: "0g",
      },
      servingSize: "250ml",
    },
    {
      id: 29,
      name: "Бутылка с фильтром",
      description: "Удобная бутылка для воды с фильтром, которая позволяет пить чистую воду в любых условиях.",
      price: 700,
      category: "Аксессуары",
      image: "https://expedition.kg/products/Filtrbutylka_AKVAFOR_Siti_obem_05_l_Aquaphor-bottles-colours.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 30,
      name: "Спортивные шорты",
      description: "Легкие и дышащие шорты для тренировок. Идеальны для занятий спортом в теплую погоду.",
      price: 800,
      category: "Одежда",
      image: "https://avidevelopment-m.ru/wp-content/uploads/2020/10/419-2.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 31,
      name: "Спортивные кроссовки",
      description: "Кроссовки, специально разработанные для тренировок. Обеспечивают поддержку и комфорт во время занятий.",
      price: 2500,
      category: "Одежда",
      image: "https://f-asc-l.mncdn.com/livephotos/1012A948-100/1012A948-100_03_2.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 32,
      name: "Спортивная майка",
      description: "Легкая и удобная майка для тренировок. Обеспечивает отличную воздухопроницаемость.",
      price: 600,
      category: "Одежда",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTryFaOc1VZN_KiFb1GieoXROExpS8oMNMX3Q&s",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 33,
      name: "Фитнес-рукава",
      description: "Рукава для поддержки мышц рук во время тренировок. Обеспечивают дополнительную защиту и комфорт.",
      price: 500,
      category: "Одежда",
      image: "https://images.uzum.uz/cosf88vfrr80f2gk1sjg/original.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 34,
      name: "Спортивные носки",
      description: "Удобные носки для тренировок, которые обеспечивают комфорт и поддержку.",
      price: 300,
      category: "Одежда",
      image: "https://www.sport-safe.ru/components/com_virtuemart/shop_image/product/resized/oo_67XUU7151_71.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 35,
      name: "Спортивные шапки",
      description: "Шапки для защиты от холода во время тренировок на открытом воздухе. Обеспечивают тепло и комфорт.",
      price: 400,
      category: "Одежда",
      image: "https://m.sportkult.ru/ipreview/goods/580/580/craft-core-backcountry-knit-hat-black.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 36,
      name: "Спортивная сумка",
      description: "Удобная сумка для переноски спортивной экипировки. Имеет множество карманов для хранения.",
      price: 1000,
      category: "Аксессуары",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdWJG9CYyCitnTWudVelZYk-Dn_DYFi9gPug&s",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 37,
      name: "Спортивный рюкзак",
      description: "Просторный рюкзак для переноски спортивной экипировки и личных вещей. Обеспечивает удобство и практичность.",
      price: 1500,
      category: "Аксессуары",
      image: "https://inter-sport.s3.amazonaws.com/products/DH7709/hyper%20royal_405/DH7709-1_resized_400X400.png",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 38,
      name: "Коврик для йоги",
      description: "Коврик для занятий йогой, обеспечивающий комфорт и сцепление с поверхностью.",
      price: 1200,
      category: "Аксессуары",
      image: "https://telefon.kg/image/cache/catalog/new/Aksessuary/Fitnes/Yoga/Kovrik/1-1200x800.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 39,
      name: "Спортивный плед",
      description: "Удобный плед для использования на свежем воздухе. Обеспечивает тепло и комфорт в любое время года.",
      price: 900,
      category: "Аксессуары",
      image: "https://jako-oren.ru/assets/images/products/11653/hw0117-04-p02.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },
    {
      id: 40,
      name: "Спортивный ковер",
      description: "Ковер для тренировок, обеспечивающий сцепление и комфорт во время занятий.",
      price: 1500,
      category: "Аксессуары",
      image: "https://fitpoint.ee/image/cache/catalog/power%20system/CleanShot%202023-01-27%20at%2016.59.18@2x-800x800.jpg",
      nutrients: {
        protein: "0g",
        carbs: "0g",
        fat: "0g",
      },
      servingSize: "n/a",
    },  
  ];
  
  export default products;
  